### PR TITLE
#137791351 Integrate Bugsnag For Error Reporting

### PR DESCRIPTION
**Pull request by andela-akolawole**
#### What does this PR do?
This PR integrates Bugsnag
#### Description of Task to be completed?
Integration of an error reporting service called bugsnag. This should report production errors and app crashes
#### How should this be manually tested?
This can only run on production.
To test follow the steps below:
- Clone the repo
- Navigate to any react component file
- Manually throw an error like below
```js
throw new Error("This is a manual error");
```
- After save, run this command in your terminal/command-line
`npm run build`
- After the build is done deploy the app.
- Check your bugsnag account
##### P.S
Before running `npm run build`, add some env variables
```js
BUGSNAG_API='d23kj23jn2nj3nh13923bv423b23jb4j'
NODE_ENV='production'
````
#### What are the relevant pivotal tracker stories?
#137791351
#### Questions:

### CODE REVIEW

**Comment by andela-bmakinwa** [comment]
@andela-akolawole if I try to `Rebase and merge` this PR, I get that there are merge conflicts that need to be fixed. Why do we have old commit messages that have been refactored reflected on this branch? 

Also, it doesn't seem like you re-built the application before pushing, kindly ensure that you do that as the bundled file is what's been rendered.

Please fix.

**Comment by andela-akolawole** [comment]
@andela-bmakinwa The reason we have some old commits is because the branch was created when I started the task.

**Comment by andela-akolawole** [comment]
As for the merge conflict, I don't see any.
conflicts

**Comment by andela-akolawole** [comment]
Deleting this branch because of issues with the commit history

**Pull request closed without merging**
