### PR TITLE
adds the readme to the home page

### PR DESCRIPTION
**Pull request by andela-iamadi**
This PR adds a basic readme to the root readme of the frontend. The readme covers what the project is about and how devs could contribute.

### CODE REVIEW

**Comment by andela-cdaniel** [comment]
Nice work man. Apart from the slight error in one part of the readme (where you have the sentence `You've definitely` <s>being</s> been `in this situation before:` under the *why zhishi?* header), it looks good to me.

We should test it out by pointing someone to the readme and using feedback from the person, we'll be able to appropriately determine if the readme conveys enough information to help a person understand what zhishi is all about and how to get started with contributing towards the codebase.

**Comment by andela-iamadi** [comment]
Yeah? Lol! Edited. Nice catch 👏 
I like the test-with-feedback idea. Should this happen before the merge?

**Comment by andela-iamadi** [comment]
Lol! Edited. Nice catch 👏 

I like the test-with-feedback idea. Should this happen _before_ the merge?

**Comment by andela-iamadi** [comment]
The PR now contains the tag readme too, plus some more tests

**Comment by andela-cdaniel** [comment]
About whether is should be merged now or later (when it has been reviewed by a potential contributor), It looks good to me already and we can always update it if need be. If you're not making any more changes, then by all means, carry on with the merge.

**Comment by andela-iamadi** [comment]
Alright. Cool. Merging now

**Pull request merged**
